name: Release to staging
on:
  push:
    branch: ['master'] #TODO For deploy to stage allow any branch. For deploy to prod allow only master with tag

jobs:
  prepare_stage_deploy:
    name: test stage
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and run yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq w k8s/values/stage.yaml "image" "repo.io/project/service:v0.8.29-sha" > k8s/values/stage.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Set image for deploy
  prepare_prod_deploy:
    name: test prod
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event.label.*.name == 'prod' }}
      - run: echo prod with "${GITHUB_SHA}" and "${GITHUB_REF}"
