name: Release to staging
on:
  push:
    branch: ['master']

jobs:
  prepare_stage_deploy:
    name: test
    if: ${{ github.event.label.name == 'stage' }}
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1
      - run: echo stage
  prepare_prod_deploy:
    name: test
    if: ${{ github.event.label.name == 'prod' }}
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1
      - run: echo prod
