name: Release to staging
on:
  push:
    branch: ['master']

jobs:
  prepare_stage_deploy:
    name: test stage
    runs-on: ubuntu-18.04
    if: ${{ github.event.label.*.name == 'stage' }}

    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1
      - run: echo stage
  prepare_prod_deploy:
    name: test prod
    runs-on: ubuntu-18.04
    if: ${{ github.event.label.*.name == 'prod' }}

    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1
      - run: echo prod

#See https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label
