name: Release to staging
on:
  push:
    branch: ['master'] #TODO For deploy to stage allow any branch. For deploy to prod allow only master with tag

jobs:
  prepare_stage_deploy:
    name: test stage
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        if: ${{ github.event.label.*.name == 'stage' }}
        with:
          depth: 1
        run: echo stage with "${GITHUB_SHA}" and "${GITHUB_REF}"
      - name: Modify image tag
        uses: mikefarah/yq@3.4.1
        if: ${{ github.event.label.*.name == 'stage' }}
        run: yq w k8s/values/stage.yaml "image" "repo.io/project/service:v0.8.29-sha"
  prepare_prod_deploy:
    name: test prod
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event.label.*.name == 'prod' }}
        with:
          depth: 1
      - run: echo prod with "${GITHUB_SHA}" and "${GITHUB_REF}"
